/**
 * Styles for ExportDialog component
 * Extracted for maintainability
 */

import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  dialog: {
    backgroundColor: 'var(--bg-card)',
    borderRadius: '12px',
    width: '560px',
    maxWidth: '90vw',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
    border: '1px solid var(--border-default)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid var(--border-default)',
    flexShrink: 0,
  },
  title: {
    fontSize: '18px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    padding: '4px',
    display: 'flex',
    borderRadius: '4px',
  },
  content: {
    padding: '20px',
    overflowY: 'auto',
    flex: 1,
  },
  section: {
    marginBottom: '24px',
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    marginBottom: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  courseList: {
    maxHeight: '150px',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    border: '1px solid var(--border-default)',
    borderRadius: '8px',
    padding: '8px',
  },
  courseItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 8px',
    borderRadius: '4px',
    cursor: 'pointer',
    color: 'var(--text-primary)',
  },
  courseActions: {
    display: 'flex',
    gap: '8px',
    marginTop: '8px',
  },
  linkButton: {
    background: 'none',
    border: 'none',
    color: 'var(--color-blue)',
    cursor: 'pointer',
    fontSize: '13px',
    padding: 0,
  },
  checkbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
    accentColor: 'var(--color-blue)',
  },
  includeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
  },
  includeOption: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    border: '1px solid var(--border-default)',
    borderRadius: '8px',
    cursor: 'pointer',
    color: 'var(--text-primary)',
    backgroundColor: 'var(--bg-card)',
    outline: 'none',
  },
  includeOptionSelected: {
    backgroundColor: 'var(--color-selection-bg)',
    borderColor: 'var(--color-selection-border)',
  },
  filtersRow: {
    display: 'flex',
    gap: '16px',
    marginBottom: '12px',
  },
  filterGroup: {
    flex: 1,
  },
  filterLabel: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    marginBottom: '6px',
    display: 'block',
  },
  select: {
    width: '100%',
    padding: '8px 12px',
    border: '1px solid var(--border-default)',
    borderRadius: '6px',
    backgroundColor: 'var(--bg-card)',
    color: 'var(--text-primary)',
    fontSize: '14px',
  },
  formatOptions: {
    display: 'flex',
    gap: '12px',
  },
  formatButton: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    padding: '16px 12px',
    border: '2px solid var(--border-default)',
    borderRadius: '8px',
    backgroundColor: 'var(--bg-card)',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    color: 'var(--text-primary)',
    minHeight: '100px',
    outline: 'none',
  },
  formatButtonSelected: {
    borderColor: 'var(--color-selection-border)',
    backgroundColor: 'var(--color-selection-bg)',
  },
  formatLabel: {
    fontSize: '14px',
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  formatDesc: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
  },
  encryptSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    border: '1px solid var(--border-default)',
    borderRadius: '8px',
    marginBottom: '12px',
    color: 'var(--text-primary)',
  },
  passwordInput: {
    flex: 1,
    padding: '8px 12px',
    border: '1px solid var(--border-default)',
    borderRadius: '6px',
    backgroundColor: 'var(--bg-card)',
    color: 'var(--text-primary)',
    fontSize: '14px',
  },
  passwordStrength: {
    display: 'flex',
    gap: '4px',
    marginTop: '8px',
  },
  strengthBar: {
    flex: 1,
    height: '4px',
    borderRadius: '2px',
    backgroundColor: 'var(--border-default)',
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderTop: '1px solid var(--border-default)',
    gap: '12px',
    flexShrink: 0,
    backgroundColor: 'var(--bg-card)',
  },
  footerInfo: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
  },
  footerButtons: {
    display: 'flex',
    gap: '12px',
  },
  cancelButton: {
    padding: '10px 20px',
    border: '1px solid var(--border-default)',
    borderRadius: '8px',
    background: 'none',
    cursor: 'pointer',
    color: 'var(--text-primary)',
    fontSize: '14px',
  },
  exportButton: {
    padding: '10px 20px',
    border: 'none',
    borderRadius: '8px',
    backgroundColor: 'var(--color-navy)',
    color: 'white',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  exportButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  statusMessage: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    borderRadius: '8px',
    marginBottom: '16px',
    fontSize: '14px',
  },
  successMessage: {
    backgroundColor: 'var(--color-success-bg)',
    color: 'var(--color-success)',
  },
  errorMessage: {
    backgroundColor: 'var(--color-error-bg)',
    color: 'var(--color-error)',
  },
};
